import streamlit as st
import streamlit.components.v1 as components

# Page config layout configuration
st.set_page_config(page_title="Hassan Malik Bot Pro", layout="centered", initial_sidebar_state="collapsed")

# Native system frame reset mask
st.markdown("<style>#MainMenu {visibility: hidden;} footer {visibility: hidden;} header {visibility: hidden;} .block-container {padding: 0px !important;} iframe {border: none !important;}</style>", unsafe_allow_html=True)

# Safe dictionary variables initialization
data_map = {}

# Slicing html chunks into small pieces to pass through compiler safely
data_map["s1"] = "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no'>"
data_map["s2"] = "<title>Hassan Malik Bot Pro</title><script src='https://jsdelivr.net'></script><script src='https://unpkg.com'></script>"
data_map["s3"] = "<style>body{background-color:#030712;font-family:sans-serif;-webkit-tap-highlight-color:transparent;}.neon-blue{text-shadow:0 0 15px rgba(14,165,233,0.8);}.neon-gold{box-shadow:0 0 15px rgba(234,179,8,0.2);border:1px solid rgba(234,179,8,0.4);}.custom-scroll::-webkit-scrollbar{height:3px;}.custom-scroll::-webkit-scrollbar-thumb{background:#1e293b;border-radius:4px;}</style></head>"
data_map["s4"] = "<body class='flex justify-center items-center h-screen overflow-hidden bg-slate-950 p-2'><div class='w-full max-w-md h-[96vh] bg-gradient-to-b from-slate-950 via-slate-900 to-black rounded-2xl p-4 shadow-2xl border border-slate-800 flex flex-col justify-between overflow-hidden'><div class='space-y-2.5'><div class='flex items-center justify-between'><div class='flex items-center gap-3'><div class='w-11 h-11 bg-gradient-to-tr from-cyan-400 via-blue-600 to-indigo-600 rounded-xl flex items-center justify-center p-0.5 shadow-lg shadow-blue-500/20'><div class='w-full h-full bg-slate-950 rounded-[10px] flex items-center justify-center'><i data-lucide='bot' class='w-6 h-6 text-cyan-400'></i></div></div>"
data_map["s5"] = "<div><h1 class='text-xl font-black tracking-tight text-white neon-blue'>Hassan Malik Bot</h1><div class='flex items-center gap-1.5 mt-0.5'><span class='text-[9px] font-bold bg-blue-500/20 text-blue-400 px-1.5 py-0.5 rounded border border-blue-500/30 flex items-center gap-1'><span class='w-1 h-1 rounded-full bg-blue-400 animate-pulse'></span> AI BOT</span><span class='text-[9px] font-black bg-gradient-to-r from-amber-500 to-yellow-400 text-slate-950 px-2 py-0.5 rounded shadow'>PRO MAX</span></div></div></div>"
data_map["s6"] = "<div class='text-right bg-slate-900/60 p-2 rounded-xl border border-slate-800/80'><div class='flex items-center justify-end gap-1.5 text-emerald-400 font-bold text-[10px]'><span class='w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse'></span> ONLINE</div><div class='text-[9px] text-gray-400 mt-0.5 font-medium'>Active Users: 1M+</div></div></div><div class='bg-gradient-to-r from-amber-500/10 via-yellow-500/20 to-amber-500/10 rounded-xl p-2 text-center neon-gold flex items-center justify-center gap-2'><i data-lucide='crown' class='w-3.5 h-3.5 text-yellow-400 animate-bounce'></i><span class='text-[10px] font-black uppercase tracking-wider text-yellow-300'>85% - 90% WIN RATE ACCURACY LOCKED</span></div>"
data_map["s7"] = "<div><label class='block text-[9px] font-bold text-slate-400 uppercase tracking-wider mb-1 flex items-center gap-1'><i data-lucide='globe' class='w-3 h-3 text-cyan-400'></i> Select Market Mode</label><div class='grid grid-cols-2 gap-1.5 bg-slate-950 p-1 rounded-xl border border-slate-800'><button id='btn-live' onclick=\"setMarket('LIVE')\" class='py-1.5 rounded-lg text-[10px] font-black uppercase transition-all flex items-center justify-center gap-1 text-slate-400 hover:text-white cursor-pointer'>Live Market</button><button id='btn-otc' onclick=\"setMarket('OTC')\" class='py-1.5 rounded-lg text-[10px] font-black uppercase transition-all flex items-center justify-center gap-1 bg-gradient-to-r from-cyan-600 to-blue-600 text-white shadow-lg cursor-pointer'>OTC Market</button></div></div>"
data_map["s8"] = "<div><label class='block text-[9px] font-bold text-slate-400 uppercase tracking-wider mb-1 flex items-center gap-1'><i data-lucide='layers' class='w-3 h-3 text-cyan-400'></i> Asset Selection Matrix</label><div class='relative'><select id='asset-selector' onchange='clearSignalBox()' class='w-full bg-slate-950 border border-slate-800 text-white rounded-xl p-2 text-xs font-bold focus:outline-none appearance-none cursor-pointer'></select><div class='absolute right-3 top-2.5 pointer-events-none text-slate-400'><i data-lucide='chevron-down' class='w-3.5 h-3.5'></i></div></div></div>"
data_map["s9"] = "<div><label class='block text-[9px] font-bold text-slate-400 uppercase tracking-wider mb-1 flex items-center gap-1'><i data-lucide='clock' class='w-3 h-3 text-cyan-400'></i> Chart Timeframe (Candle Period)</label><div class='flex overflow-x-auto gap-1 pb-1 custom-scroll snap-x'>"
data_map["s10"] = "<button onclick=\"setTimeframe(this,'5s','5 Seconds')\" class='tf-btn snap-start shrink-0 px-2.5 py-1 rounded-lg text-[10px] font-bold bg-cyan-600 text-white border border-cyan-500/20 cursor-pointer'>5s</button><button onclick=\"setTimeframe(this,'15s','15 Seconds')\" class='tf-btn snap-start shrink-0 px-2.5 py-1 rounded-lg text-[10px] font-bold bg-slate-950 text-slate-400 border border-slate-800 cursor-pointer'>15s</button><button onclick=\"setTimeframe(this,'30s','30 Seconds')\" class='tf-btn snap-start shrink-0 px-2.5 py-1 rounded-lg text-[10px] font-bold bg-slate-950 text-slate-400 border border-slate-800 cursor-pointer'>30s</button><button onclick=\"setTimeframe(this,'1m','1 Minute')\" class='tf-btn snap-start shrink-0 px-2.5 py-1 rounded-lg text-[10px] font-bold bg-slate-950 text-slate-400 border border-slate-800 cursor-pointer'>1m</button><button onclick=\"setTimeframe(this,'2m','2 Minutes')\" class='tf-btn snap-start shrink-0 px-2.5 py-1 rounded-lg text-[10px] font-bold bg-slate-950 text-slate-400 border border-slate-800 cursor-pointer'>2m</button><button onclick=\"setTimeframe(this,'5m','5 Minutes')\" class='tf-btn snap-start shrink-0 px-2.5 py-1 rounded-lg text-[10px] font-bold bg-slate-950 text-slate-400 border border-slate-800 cursor-pointer'>5m</button><button onclick=\"setTimeframe(this,'15m','15 Minutes')\" class='tf-btn snap-start shrink-0 px-2.5 py-1 rounded-lg text-[10px] font-bold bg-slate-950 text-slate-400 border border-slate-800 cursor-pointer'>15m</button><button onclick=\"setTimeframe(this,'30m','30 Minutes')\" class='tf-btn snap-start shrink-0 px-2.5 py-1 rounded-lg text-[10px] font-bold bg-slate-950 text-slate-400 border border-slate-800 cursor-pointer'>30m</button><button onclick=\"setTimeframe(this,'1h','1 Hour')\" class='tf-btn snap-start shrink-0 px-2.5 py-1 rounded-lg text-[10px] font-bold bg-slate-950 text-slate-400 border border-slate-800 cursor-pointer'>1h</button><button onclick=\"setTimeframe(this,'4h','4 Hours')\" class='tf-btn snap-start shrink-0 px-2.5 py-1 rounded-lg text-[10px] font-bold bg-slate-950 text-slate-400 border border-slate-800 cursor-pointer'>4h</button></div></div>"
data_map["s11"] = "<div class='bg-slate-950 p-2 rounded-xl border border-slate-800 flex justify-between items-center text-[10px]'><div class='text-slate-400 font-bold flex items-center gap-1'><i data-lucide='timer' class='w-3.5 h-3.5 text-amber-400'></i> Trade Expiration Expiry:</div><div id='expiration-label' class='font-black text-amber-400 bg-amber-500/10 px-2 py-0.5 rounded border border-amber-500/20'>5 Seconds</div></div></div>"
data_map["s12"] = "<div class='flex-1 flex items-center justify-center my-1.5 min-h-[135px]'><div id='signal-box' class='w-full p-3 rounded-xl border border-dashed border-slate-800 text-center bg-slate-950/20'><i data-lucide='radar' class='w-6 h-6 text-slate-600 mx-auto mb-1 animate-pulse'></i><div class='text-[10px] text-slate-400 font-black uppercase tracking-wider'>Hassan Malik Bot Matrix</div><div class='text-[9px] text-slate-500 mt-0.5 max-w-[280px] mx-auto'>Ready to scan live structures, trend lines, and confirmation candle logic for the next trade direction execution.</div></div></div>"
data_map["s13"] = "<div class='space-y-2.5'><button id='generate-btn' onclick='processHighAccuracySignal()' class='w-full bg-gradient-to-r from-cyan-500 via-blue-600 to-indigo-600 text-white font-black uppercase text-xs tracking-widest py-3.5 rounded-xl hover:brightness-105 active:scale-[0.99] transition-all cursor-pointer flex items-center justify-center gap-1.5 shadow-xl shadow-blue-500/10'><i data-lucide='zap' class='w-3.5 h-3.5 fill-white text-yellow-300'></i> GENERATE SIGNAL</button><div class='bg-slate-950/80 p-2 rounded-xl border border-slate-900 grid grid-cols-3 gap-1 text-center text-[9px]'><div><span class='block text-slate-500 font-semibold'>Trend Tracking</span><span class='block font-bold text-cyan-400 mt-0.5 text-[8px]'>Auto-Higher TF</span></div><div class='border-x border-slate-800'><span class='block text-slate-500 font-semibold'>Confirmation</span><span class='block font-bold text-indigo-400 mt-0.5 text-[8px]'>Next Candle Fix</span></div><div><span class='block text-slate-500 font-semibold'>Strategy Engine</span><span class='block font-bold text-yellow-400 mt-0.5 text-[8px]'>85%-90% Verified</span></div></div>"
data_map["s14"] = "<div class='text-center text-[8px] text-slate-600 font-black tracking-wider uppercase'>🤖 DESIGNED ACCORDING TO HASSAN MALIK BOT PRO QUOTEX MATRIX</div></div></div>"
data_map["s15"] = "<script>const liveAssets=['EUR/USD (LIVE)','USD/JPY (LIVE)','GBP/USD (LIVE)','AUD/USD (LIVE)','USD/CAD (LIVE)','USD/CHF (LIVE)','EUR/JPY (LIVE)','EUR/GBP (LIVE)','NZD/USD (LIVE)','AUD/NZD (LIVE)','EUR/CAD (LIVE)','GBP/MXN (LIVE)','USD/BRL (LIVE)','EUR/AUD (LIVE)','AUD/JPY (LIVE)','CAD/JPY (LIVE)','USD/MXN (LIVE)','CHF/JPY (LIVE)'];"
